[package]
name = "vector-db-from-scratch-datafusion"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "vector_datafusion"

[dependencies]
async-trait.workspace = true
datafusion.workspace = true
vector-db-from-scratch-core.workspace = true

[dev-dependencies]
datafusion-cli.workspace = true
sqllogictest.workspace = true
tokio.workspace = true
url.workspace = true

[lints]
workspace = true
