[workspace]
members = [
    "vector-core",
    "vector-core-starter",
    "vector-datafusion",
    "vector-datafusion-starter",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
rust-version = "1.88"

[workspace.dependencies]
async-trait = "=0.1.91"
datafusion = { version = "=54.1.0", default-features = false, features = ["nested_expressions", "sql"] }
sqllogictest = "=0.29.1"
tokio = { version = "=1.53.1", features = ["macros", "rt-multi-thread"] }

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
