name: mdbook gh pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup rust toolchain
        run: rustup show
      - uses: taiki-e/install-action@mdbook
      - run: mv tutorial/theme/head.hbs._ tutorial/theme/head.hbs
      - run: cd tutorial && mdbook build
      - name: upload dist
        uses: actions/upload-pages-artifact@v3
        with:
          path: tutorial/book/
  deploy:
    runs-on: ubuntu-latest
    # Add a dependency to the build job
    needs: build
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: deploy to gh pages
        id: deployment
        uses: actions/deploy-pages@v4 
